info:
  name: 04-deql-routes
  type: http
  seq: 4

http:
  method: GET
  url: "{{baseUrl}}/{{deql_org_id}}/deql/registry/routes"
  auth: inherit

runtime:
  assertions:
    - expression: res.status
      operator: eq
      value: "200"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
